# -*- coding: utf-8 -*-
"""cost_benefit_analysis_framework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Vqa-qH-0WfZh8ngtet-l9bN-g1ILRKT

# Choosing AI Models: A Cost-Benefit Analysis Framework
Standard benchmarks and leaderboards measure an AI model's raw capability, but they don't tell the whole story. They ignore crucial, real-world factors that every developer and business must face: your budget, your time, and the actual cost when a model fails and a human has to intervene.

This document presents a simple framework to move beyond abstract accuracy and calculate the total expected monetary cost of using an AI model for a specific task. By factoring in API fees, the probability of success, the cost of retries, and the financial impact of complete failure, you can make a rational, data-driven decision. It helps you answer the real question: which model provides the most value for your specific workflow, not just the one with the highest benchmark score.
##  Variable definitions (per task)

| Symbol | Meaning | Typical unit |
|---|---|---|
| p | first-attempt success probability | 0–1 |
| c | cost of the **first** attempt (API \$ + your prompting/inspection time monetised at v) | \$ |
| r | max **retries** you are willing to pay for (≥ 0) | integer |
| f | cost of **one** retry (API \$ + your time \$; often f ≈ c) | \$ |
| F | fallback cost if every AI attempt fails (human dev, rewrite, etc.) | \$ |
| t | **extra** hours you lose on final failure (context-switching, re-spec, hand-off …) | h |
| v | value of your time | \$/h |


##  Underlying Assumptions

*   The probability of success `p` is independent and constant for each attempt.
*   The cost of each retry `f` is constant.

##  Core probabilities

Total probability that the model succeeds within the allowed `r+1` attempts:
$$P_{\text{success}} = 1 - (1 - p)^{r+1}$$

##  Expected cost when the model **eventually succeeds**

We always pay `c` once. Retries are paid only on earlier failure, and we condition on the set of successful outcomes.

Expected number of retries **given eventual success**:
$$E[R \mid \text{succ}] = \frac{1 - p}{p} \cdot \frac{1 - (1 - p)^{r+1} - (r+1)\,p\,(1 - p)^r}{1 - (1 - p)^{r+1}}$$

*(**Derivation note:** This is derived from the mean of a geometric distribution, conditional on success occurring within the first `r+1` trials.)*

Hence, the expected cost **given eventual success**:
$$C_{\text{success}} = c + f \cdot E[R \mid \text{succ}]$$

##  Expected cost when the model **finally fails**

On final failure, we have made all `r+1` attempts (the first attempt plus `r` retries), then pay the fallback penalty.

The cost is therefore:
$$C_{\text{fail}} = c + r\,f + F + t\,v$$

##  Total expected monetary cost of the task

$$\text{EV}_{\text{task}} = P_{\text{success}} \cdot C_{\text{success}} + (1 - P_{\text{success}}) \cdot C_{\text{fail}}$$

##  Sanity-check: single-shot (no retries, r = 0)

$$\text{EV}_{\text{task}} = p \cdot c + (1 - p)(c + F + t\,v) = c + (1 - p)(F + t\,v)$$

##  Worked micro-example

| p | r | c | f | F | t | v |
|---|---|---|---|---|---|---|
| 0.6 | 2 | \$1 | \$1 | \$10 | 1 h | \$50 h⁻¹ |

- $$P_{\text{success}} = 1 - 0.4^{3} = 0.936$$
- $$E[R \mid \text{succ}] = \frac{0.4}{0.6} \cdot \frac{1 - 0.4^{3} - 3 \cdot 0.6 \cdot 0.4^{2}}{0.936} \approx 0.462$$ retries
- $$C_{\text{success}} = 1 + 1 \cdot 0.462 \approx \$1.46$$
- $$C_{\text{fail}} = 1 + 2 \cdot 1 + 10 + 1 \cdot 50 = \$63$$
- $$\text{EV}_{\text{task}} = 0.936 \cdot 1.46 + (1 - 0.936) \cdot 63 \approx \$5.40$$

##  Time-Constrained Retry Budget (optional extension)

If you want to give the AI **only as many retries as fit inside the time a human would spend**, set your maximum retries `r` to:
$$r_{\text{max}} = \left\lfloor \frac{T_{\text{human}}}{T_{\text{AI}}} \right\rfloor - 1$$

where:
- $$T_{\text{human}}$$ = human hours for the task
- $$T_{\text{AI}}$$ = AI hours per attempt (wall-clock + your inspection time)

Then plug $$r = r_{\text{max}}$$ into the formulas above to obtain a **time-fair** EV comparison.

##  How to collect the numbers in practice

1.  Pick 30–50 representative tasks.
2.  For each task / model pair record:
    -   pass/fail on first try → p
    -   API \$ + minutes you spent → c
    -   retry cost f (usually ≈ c)
    -   did you stop early? → real r used
    -   fallback you would actually pay → F
    -   extra hours lost if all failed → t
3.  Average EV_task across tasks → EV_model.
4.  Choose the model with the **lowest** EV_model.

##  Why this beats leaderboards

Leaderboards optimise for **accuracy under infinite patience**; your wallet optimises for **accuracy under finite money and time**.
The EV formula converts both dimensions into a single currency (\$) and lets you decide whether a 4% absolute accuracy boost is worth a 3× cost increase.

##  TL;DR

Compute:
“probability it works” × “what you pay when it works”
\+
“probability it bombs” × “what you pay when it bombs”

Pick the model whose **average \$** across your own tasks is lowest.
"""

import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
from typing import Dict, List, Tuple

def ev_task_vectorized(p, r, c, f, F, t, v):
    """Your original function - keeping as-is"""
    q = 1 - p
    k = r + 1
    P_success = 1 - q**k
    p_safe = np.where(p == 1, 1 - 1e-9, p)
    numerator = 1 - q**k - k * p_safe * q**(k - 1)
    E_R_succ = np.divide((q / p_safe) * numerator, P_success,
                         out=np.zeros_like(P_success, dtype=float),
                         where=P_success!=0)
    C_success = c + f * E_R_succ
    C_fail = c + r * f + F + t * v
    EV_task = P_success * C_success + (1 - P_success) * C_fail
    return EV_task, P_success

class TaskDAG:
    """
    Represents a workflow as a DAG where task success probabilities
    propagate through dependencies.
    """

    def __init__(self, base_params: Dict):
        """
        Args:
            base_params: dict with keys 'F', 't', 'v' for fallback costs
        """
        self.G = nx.DiGraph()
        self.base_params = base_params
        self.results = {}  # Store computed results per node

    def add_task(self, name: str, p_intrinsic: float, c: float, r: int = 2,
                 level: str = "low", criticality: float = 1.0):
        """
        Add a task node to the DAG.

        Args:
            name: Task identifier
            p_intrinsic: Success probability assuming perfect inputs
            c: Cost per attempt
            r: Max retries
            level: "high" (planning/arch) or "low" (implementation)
            criticality: Multiplier for how important this task is (default 1.0)
        """
        self.G.add_node(name,
                       p_intrinsic=p_intrinsic,
                       c=c,
                       r=r,
                       level=level,
                       criticality=criticality)

    def add_dependency(self, upstream: str, downstream: str,
                       quality_degradation: float = 0.9):
        """
        Add a dependency edge.

        Args:
            upstream: Parent task
            downstream: Child task
            quality_degradation: How much upstream failure affects downstream
                                (1.0 = full propagation, 0.0 = no effect)
        """
        self.G.add_edge(upstream, downstream, degradation=quality_degradation)

    def compute_effective_p(self, node: str, upstream_success_probs: Dict[str, float]) -> float:
        """
        Calculate effective success probability accounting for upstream failures.

        Uses a multiplicative model where each failed parent reduces the
        effective capability of the current node.
        """
        p_intrinsic = self.G.nodes[node]['p_intrinsic']

        # No parents = just use intrinsic probability
        parents = list(self.G.predecessors(node))
        if not parents:
            return p_intrinsic

        # Compute inherited quality from parents
        inherited_quality = 1.0
        for parent in parents:
            parent_success_prob = upstream_success_probs[parent]
            degradation = self.G.edges[parent, node]['degradation']

            # Model: each parent's failure proportionally reduces our capability
            # If parent has 80% success rate with 0.9 degradation factor:
            # inherited_quality *= 0.8 + (1-0.8) * (1-0.9) = 0.82
            inherited_quality *= (parent_success_prob +
                                (1 - parent_success_prob) * (1 - degradation))

        # Effective probability is intrinsic capability scaled by input quality
        return p_intrinsic * inherited_quality

    def compute_dag_ev(self, show_breakdown: bool = False) -> Tuple[float, Dict]:
        """
        Compute total expected cost for the entire workflow.

        Returns:
            (total_ev, node_details) where node_details contains per-node metrics
        """
        topo_order = list(nx.topological_sort(self.G))
        total_ev = 0
        upstream_success_probs = {}
        node_details = {}

        for node in topo_order:
            # Get effective probability accounting for dependencies
            p_eff = self.compute_effective_p(node, upstream_success_probs)

            # Get node parameters
            c = self.G.nodes[node]['c']
            r = self.G.nodes[node]['r']
            criticality = self.G.nodes[node]['criticality']

            # Calculate EV for this node
            node_ev, node_success_prob = ev_task_vectorized(
                np.array([p_eff]),
                np.array([r]),
                np.array([c]),
                np.array([c]),  # f ≈ c
                np.array([self.base_params['F']]),
                np.array([self.base_params['t']]),
                np.array([self.base_params['v']])
            )

            # Weight by criticality
            weighted_ev = node_ev[0] * criticality
            total_ev += weighted_ev

            # Store results for downstream propagation
            upstream_success_probs[node] = node_success_prob[0]
            node_details[node] = {
                'p_intrinsic': self.G.nodes[node]['p_intrinsic'],
                'p_effective': p_eff,
                'p_success': node_success_prob[0],
                'ev': node_ev[0],
                'weighted_ev': weighted_ev,
                'criticality': criticality,
                'level': self.G.nodes[node]['level']
            }

        if show_breakdown:
            self._print_breakdown(node_details, total_ev)

        return total_ev, node_details

    def _print_breakdown(self, details: Dict, total: float):
        """Pretty print the cost breakdown"""
        print("\n" + "="*80)
        print("WORKFLOW COST BREAKDOWN")
        print("="*80)
        print(f"{'Task':<20} {'Level':<8} {'p_intr':<8} {'p_eff':<8} {'p_succ':<8} {'EV($)':<10} {'Weighted($)'}")
        print("-"*80)

        for node, d in details.items():
            print(f"{node:<20} {d['level']:<8} {d['p_intrinsic']:<8.3f} "
                  f"{d['p_effective']:<8.3f} {d['p_success']:<8.3f} "
                  f"{d['ev']:<10.2f} {d['weighted_ev']:.2f}")

        print("-"*80)
        print(f"{'TOTAL':<20} {'':<8} {'':<8} {'':<8} {'':<8} {'':<10} ${total:.2f}")
        print("="*80 + "\n")

    def visualize(self, node_details: Dict = None, figsize=(14, 8)):
        """
        Visualize the DAG with color-coding based on effective success rates.
        """
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=figsize)

        # Left plot: Task structure
        pos = nx.spring_layout(self.G, k=2, iterations=50)

        if node_details:
            # Color by effective success probability
            node_colors = [node_details[node]['p_effective']
                          for node in self.G.nodes()]
            node_sizes = [node_details[node]['weighted_ev'] * 100 + 500
                         for node in self.G.nodes()]
        else:
            node_colors = ['lightblue'] * len(self.G.nodes())
            node_sizes = [2000] * len(self.G.nodes())

        nx.draw(self.G, pos, with_labels=True, node_color=node_colors,
               node_size=node_sizes, font_size=9, arrows=True,
               cmap='RdYlGn', vmin=0.5, vmax=1.0, ax=ax1)
        ax1.set_title("Task Dependency Graph\n(size = weighted cost, color = effective p)")

        # Right plot: Cost breakdown
        if node_details:
            nodes = list(node_details.keys())
            weighted_costs = [node_details[n]['weighted_ev'] for n in nodes]
            colors = ['#ff6b6b' if node_details[n]['level'] == 'high'
                     else '#4ecdc4' for n in nodes]

            ax2.barh(nodes, weighted_costs, color=colors)
            ax2.set_xlabel('Weighted Expected Cost ($)')
            ax2.set_title('Cost Contribution by Task\n(red = high-level, teal = low-level)')
            ax2.grid(axis='x', alpha=0.3)

        plt.tight_layout()
        plt.show()

    def sensitivity_analysis(self, node: str, p_range: np.ndarray = None):
        """
        Show how varying one node's p_intrinsic affects total workflow EV.

        This reveals which tasks are most critical to optimize.
        """
        if p_range is None:
            p_range = np.linspace(0.5, 0.99, 20)

        original_p = self.G.nodes[node]['p_intrinsic']
        evs = []

        for p in p_range:
            self.G.nodes[node]['p_intrinsic'] = p
            ev, _ = self.compute_dag_ev()
            evs.append(ev)

        # Restore original
        self.G.nodes[node]['p_intrinsic'] = original_p

        plt.figure(figsize=(10, 6))
        plt.plot(p_range, evs, marker='o', linewidth=2)
        plt.axvline(original_p, color='r', linestyle='--',
                   label=f'Current: p={original_p:.2f}')
        plt.xlabel(f'Success Probability for "{node}"')
        plt.ylabel('Total Workflow EV ($)')
        plt.title(f'Sensitivity: Impact of "{node}" Quality on Total Cost')
        plt.grid(True, alpha=0.3)
        plt.legend()
        plt.show()

        return p_range, evs

base_params = {'F': 20, 't': 0.5, 'v': 100}

# Scenario 1: Good planning
print("SCENARIO 1: High-quality planning (p=0.92)")
dag1 = TaskDAG(base_params)
dag1.add_task("Planning", p_intrinsic=0.92, c=2.0, r=1, level="high", criticality=2.0)
dag1.add_task("Decompose", p_intrinsic=0.90, c=1.5, r=2, level="high", criticality=1.5)
dag1.add_task("Code Task 1", p_intrinsic=0.85, c=0.3, r=3, level="low")
dag1.add_task("Code Task 2", p_intrinsic=0.85, c=0.3, r=3, level="low")
dag1.add_task("Integrate", p_intrinsic=0.88, c=0.5, r=2, level="low")
dag1.add_task("Review", p_intrinsic=0.93, c=1.8, r=1, level="high", criticality=1.3)

dag1.add_dependency("Planning", "Decompose", quality_degradation=0.95)
dag1.add_dependency("Decompose", "Code Task 1", quality_degradation=0.90)
dag1.add_dependency("Decompose", "Code Task 2", quality_degradation=0.90)
dag1.add_dependency("Code Task 1", "Integrate", quality_degradation=0.85)
dag1.add_dependency("Code Task 2", "Integrate", quality_degradation=0.85)
dag1.add_dependency("Integrate", "Review", quality_degradation=0.90)

ev1, details1 = dag1.compute_dag_ev(show_breakdown=True)

# Scenario 2: Poor planning
print("\nSCENARIO 2: Low-quality planning (p=0.65) - same models downstream")
dag2 = TaskDAG(base_params)
dag2.add_task("Planning", p_intrinsic=0.65, c=2.0, r=1, level="high", criticality=2.0)
dag2.add_task("Decompose", p_intrinsic=0.90, c=1.5, r=2, level="high", criticality=1.5)
dag2.add_task("Code Task 1", p_intrinsic=0.85, c=0.3, r=3, level="low")
dag2.add_task("Code Task 2", p_intrinsic=0.85, c=0.3, r=3, level="low")
dag2.add_task("Integrate", p_intrinsic=0.88, c=0.5, r=2, level="low")
dag2.add_task("Review", p_intrinsic=0.93, c=1.8, r=1, level="high", criticality=1.3)

dag2.add_dependency("Planning", "Decompose", quality_degradation=0.95)
dag2.add_dependency("Decompose", "Code Task 1", quality_degradation=0.90)
dag2.add_dependency("Decompose", "Code Task 2", quality_degradation=0.90)
dag2.add_dependency("Code Task 1", "Integrate", quality_degradation=0.85)
dag2.add_dependency("Code Task 2", "Integrate", quality_degradation=0.85)
dag2.add_dependency("Integrate", "Review", quality_degradation=0.90)

ev2, details2 = dag2.compute_dag_ev(show_breakdown=True)

print(f"\n{'='*80}")
print(f"COST IMPACT OF PLANNING QUALITY")
print(f"{'='*80}")
print(f"Good planning (p=0.92): ${ev1:.2f}")
print(f"Poor planning (p=0.65): ${ev2:.2f}")
print(f"Cost increase: ${ev2 - ev1:.2f} ({((ev2/ev1 - 1) * 100):.1f}%)")
print(f"{'='*80}\n")

# Visualize
dag1.visualize(details1)

# Sensitivity analysis
dag1.sensitivity_analysis("Planning")

